### ISSUE TITLE
It doesn't work on linux

### ISSUE THREAD

**Issue by totolgueimer** [Lynxdeer/AutoDeafenOld#2]
https://github.com/Lynxdeer/AutoDeafen/assets/67667018/30c4eb12-4d46-48f5-958c-8977c4312efd

**Comment by Lynxdeer** [comment]
AutoDeafen relies on the Windows API for keybinds, and I'm not going to change that- if you want, you can DM me (@lynxdeer) on discord to try and troubleshoot. You could also make a PR fixing it yourself, if you'd like, and I'd happily accept that.
